packages:
  - "apps/*"
  - "packages/*"

overrides:
  vite: ">=7.3.2"
  uuid: ">=14.0.0"
  postcss: "^8.5.12"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild
  - msw
  - supabase
  - unrs-resolver
